[package]
name = "egui-version"
version = "0.1.0"
edition = "2024"

[dependencies]
catppuccin-egui = { version = "5.5.0", default-features = false, features = ["egui32"] }
eframe = "0.32.0"
egui = "0.32.0"
env_logger = "0.11.8"
